# Model #3 for image prediction

In [1]:
import numpy as np
import pandas as pd
# from skimage import imread
from matplotlib.image import imread
import matplotlib.pyplot as plt
import os
import cv2
import random
import pickle
from sklearn.metrics import confusion_matrix, recall_score
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models,callbacks,metrics,backend
import sys
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
# sys.path.append(os.path.abspath(r'C:\Users\raulg\Documents\THEBRIDGE_DS\0.-Repo_Git\ml_alzheimer_class\src'))
sys.path.append(os.path.relpath('../src'))
import utils as ut
import math


This model aims to get a better accuracy, by adding datagen to the process

## Data loading and mix

In [2]:
x1_train,x1_test,x1_val,y1_train,y1_test,y1_val = ut.img_images_load(val_set = True)
# print(x1_train.shape)
# print(x1_test.shape)
# print(y1_train.shape)
# print(y1_test.shape)
# print(y1_val.shape)
# unique_train, counts_train = np.unique(y1_train, return_counts=True)
# unique_test, counts_test = np.unique(y1_test, return_counts=True)
# unique_val, counts_val = np.unique(y1_val, return_counts=True)
# print(np.asarray((unique_train, counts_train)).T)
# print(np.asarray((unique_test, counts_test)).T)
# print(np.asarray((unique_val, counts_val)).T)

x1_train shape (34326, 32, 32, 1)
x1_test shape (6058, 32, 32, 1)
y1_train shape (34326,)
y1_test shape (6058,)
y1_train distribution: 
 [[    0 10880]
 [    1  9520]
 [    2  8377]
 [    3  5549]]
y1_test distribution: 
 [[   0 1920]
 [   1 1680]
 [   2 1479]
 [   3  979]]
x1_val shape (6866, 32, 32, 1)
y1_val shape (6866,)
y1_val distribution: 
 [[   0 2176]
 [   1 1904]
 [   2 1676]
 [   3 1110]]


In [ ]:

# def recall_m(y_true, y_pred):
#     # Convertir y_true a one-hot encoding
#     y_true = backend.one_hot(backend.cast(y_true, 'int32'), num_classes=backend.shape(y_pred)[-1])
#     # Calcular los verdaderos positivos
#     true_positives = backend.sum(backend.round(backend.clip(y_true * y_pred, 0, 1)))
#     # Calcular los posibles positivos
#     possible_positives = backend.sum(backend.round(backend.clip(y_true, 0, 1)))
#     # Calcular el recall
#     recall = true_positives / (possible_positives + backend.epsilon())
#     return recall

In [ ]:
### COMP TIME: 
model3 = models.Sequential()
model3.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 1)))
model3.add(layers.MaxPooling2D((2, 2)))
model3.add(layers.Conv2D(64, (3, 3), activation='relu'))
model3.add(layers.MaxPooling2D((2, 2)))
model3.add(layers.Flatten())

# Capa densa con Dropout
model3.add(layers.Dense(32, activation='relu'))
model3.add(layers.Dropout(0.5))  # Dropout para reducir overfitting

model3.add(layers.Dense(4, activation='softmax'))

# Compilar el modelo
model3.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy', #sparse_categorical_crossentropy
              metrics=['accuracy'])
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# label_encoder = LabelEncoder()
# y1_train_encoded = label_encoder.fit_transform(y1_train)
# y2_test_encoded = label_encoder.transform(y1_test)
model3.fit(datagen.flow(x1_train,y1_train,batch_size=64),epochs=70,validation_data=(x1_val,y1_val), callbacks=callbacks.EarlyStopping(patience=5)
          )

c:\Users\raulg\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\raulg\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 13s 28ms/step - accuracy: 0.3475 - loss: 1.3292 - val_accuracy: 0.3276 - val_loss: 1.3670
Epoch 2/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4010 - loss: 1.2369 - val_accuracy: 0.4308 - val_loss: 1.1906
Epoch 3/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 11s 26ms/step - accuracy: 0.4188 - loss: 1.1930 - val_accuracy: 0.4234 - val_loss: 1.2007
Epoch 4/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4394 - loss: 1.1687 - val_accuracy: 0.5020 - val_loss: 1.0772
Epoch 5/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4569 - loss: 1.1411 - val_accuracy: 0.5176 - val_loss: 1.0511
Epoch 6/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4704 - loss: 1.1068 - val_accuracy: 0.5706 - val_loss: 0.9390
Epoch 7/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4889 - loss: 1.0850 - val_accuracy: 0.5392 - val_loss: 0.9655
Epoch 8/70
430/430 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.4994 - loss: 1.0484 - 

In [4]:
model3.evaluate(x1_test, y1_test)

190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6383 - loss: 0.7821


[0.7722964286804199, 0.6386595964431763]

In [5]:
y1_pred = model3.predict(x1_test)

190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [15]:
y1_pred.argmax(axis=1)

array([2, 2, 1, ..., 2, 1, 2])

In [7]:
recall_score(y1_test, model3.predict(x1_test).argmax(axis=1),average='weighted')

190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


np.float64(0.6386596236381644)

In [8]:
confusion_matrix(y1_test, model3.predict(x1_test).argmax(axis=1),normalize='pred') #,normalize='pred'

190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([[0.76128591, 0.34763948, 0.1407212 , 0.00108225],
       [0.2250342 , 0.46995708, 0.30430959, 0.0021645 ],
       [0.01367989, 0.18240343, 0.5237467 , 0.01406926],
       [0.        , 0.        , 0.03122252, 0.98268398]])